export const environment = {
  base:' http://localhost:3000',
  base_cartItems:'/cartItems',
  base_groceries:'/groceries',
  base_url:'https://7a12-117-217-127-105.ngrok-free.app/api/v1',
  get_user:"/customer/customer-details",
  register:'/customer/register',
  logIn:'/customer/login',
  getCategory_url:"/category/get-all-categories",
  change_password:"/customer/changePassword",
  add_address:"/customer/add-customer-address",
  update_profile:"/customer/update-customer",
  address_delete:"/customer/delete-customer-address",
  encrypt:"/encryption",
  address_edit:"/customer/update-customer-address",
  getAll_products:"/product/get-all-products",
  getProduct_category:"/product/get-product-by-category-id",
  order:"/order/add-order",
  order_get:"/customer/get-customer-all-orders"
};
